# default configuration
baseURL = "/"
languageCode = "en-us"
theme = "thomson-hugo"
title = "UIC Culture and Design Management Major"
summaryLength = "10"
pagination.pagerSize = 10

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify/css/themify-icons.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/animated-text/animated-text.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/animated-text/animated-text.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"


# menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About CDM"
url = "about/"
weight = 2

[[menu.main]]
parent = "About CDM"
name = "Our Vision"
url = "#/"
weight = 1

[[menu.main]]
parent = "About CDM"
name = "Curriculum"
url = "#/"
weight = 2

[[menu.main]]
parent = "About CDM"
name = "Exchange Program"
url = "#/"
weight = 2

[[menu.main]]
parent = "About CDM"
name = "Career Path"
url = "#/"
weight = 2

[[menu.main]]
name = "People"
url = "people/"
weight = 2

[[menu.main]]
parent = "People"
name = "Faculty"
url = "people/faculty"
weight = 1

[[menu.main]]
parent = "People"
name = "Students"
url = "people/students"
weight = 2

[[menu.main]]
parent = "People"
name = "Student council"
url = "people/student-council"
weight = 3

[[menu.main]]
parent = "People"
name = "Alumni"
url = "people/alumni"
weight = 4

[[menu.main]]
name = "Research"
url = "#/"
weight = 3

[[menu.main]]
name = "Show"
url = "portfolio/"
weight = 4

[[menu.main]]
name = "News"
url = "blog/"
weight = 5

[[menu.main]]
name = "FAQ"
url = "faq/"
weight = 6



# default parameters
[params]
home = "Home"
logo = "images/logo-s.png"
# contact info
mobile = "+880 2544 658 256"
email = "steve.fruits@email.com"
address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "themefisher"
description = "This is meta description"
# google analitycs
google_analitycs_id = ""
# contact form action 
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = "Copyright © Culture and Design Management Major. All Rights Reserved "

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-facebook"
link = "#"

[[params.social]]
icon = "ti-instagram"
link = "#"

[[params.social]]
icon = "ti-dribbble"
link = "#"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"
