[build]
command = "hugo"
 publish = "public"
 
# Always trigger a rebuild, even if the files haven't changed.
# See https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds
ignore = "false"

[build.environment]
HUGO_VERSION = "0.129.0"
